services:
  service:
    build:
      context: ../
      target: development
    container_name: vectix
    restart: always
    ports:
      - "5000:8000"
    volumes:
      - ../:/app
      - vectix_uploads:/app/uploads
    env_file:
      - ../envs/.env.development
    depends_on:
      - postgres
      - redis
    networks:
      - vectix_network

  postgres:
    image: postgres:16
    container_name: vectix_postgres
    restart: always
    env_file:
      - ../envs/.env.development
    environment:
      - POSTGRES_DB=${DB_NAME:-vectix}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-1234}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vectix_network

  redis:
    image: redis:7
    container_name: vectix_redis
    restart: always
    networks:
      - vectix_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: vectix_pgadmin
    restart: always
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vectix.dev
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    volumes:
      - ../pgadmin/servers.json:/pgadmin4/servers.json
      - ../pgadmin/pgpass:/pgpass
      - vectix_pgadmin_data:/var/lib/pgadmin
    user: root
    networks:
      - vectix_network

volumes:
  postgres_data:
  redis_data:
  vectix_pgadmin_data:
  vectix_uploads:

networks:
  vectix_network:
    driver: bridge
